### ISSUE TITLE
Resource deduce backend from cluster

### ISSUE THREAD

**Issue by ferranbt** [teseraio/ensemble#2]
Right now, the Resource spec looks like this:
```
apiVersion: "ensembleoss.io/v1"
kind: Resource
spec:
    backend: XX
    cluster: YY
```
The operator does not need to know the backend for the resource since it can deduce that information from the cluster to which this new resource belongs.
