### ISSUE TITLE
Cluster configuration

### ISSUE THREAD

**Issue by ferranbt** [teseraio/ensemble#6]
Add a new field to the Cluster object to represent configuration fields for the nodes. For example:
```
apiVersion: "ensembleoss.io/v1"
kind: Cluster
spec:
   backend:
      name: zookeeper
   replicas: 3
   config:
      tickTime: 1000
```
The new config field is arbitrary and checked with the webhook validation.

A later PR will address the update of this values since some values might be updated dynamically (redis configuration) and others might require rolling updates.
